### ISSUE TITLE
Make anchor links work without JS

### ISSUE THREAD

**Issue by piotrpog** [craftcms/docs#174] opened 2021-03-13 13:05 UTC
Very often when i open docs and click some anchor link, i have to wait few seconds until JS loads and page animates to my desired section. Sometimes even when i enter docs from google and already land on specific section of document, after JS loads im automatically scrolled to top. It is very annoying.

**Comment by MattWilcox** [comment] 2021-03-23 19:41
TBH, this "documentation as an app" thing is a really bad trend I see with lots of tech companies. The WWW was built to handle text heavy content, and it has a lot of tooling to make that work well at every level of the stack; from server to browser. Then you get these JS app based monstrosities which work great on a good connection on a fast machine... but like garbage on anything else.

I can't imagine the docs are going to move off of the JS framework they've built on, but I'd say building text documentation on these frameworks is always (always) a poor choice of minor bells and whistles at the expense of real tried and tested low-requirements methods. Stripe are awful for this too.

"Upgrade your machine and connection" to view the website is a bad message, but that's the reality here I imagine.

**Comment by mattstein** [comment] 2021-04-23 15:03
Thanks for the issue @piotrpog!

We’ve made improvements to fix a number of scroll issues that seem to have helped. Are you able to get this one down to a reproducible set of steps?

**Comment by mattstein** [comment] 2022-02-24 15:06
Closing since it’s been a while without any follow-up, but please let me know if this is still an issue and there are steps I can take to reproduce it.

**Closed as completed by mattstein** 2022-02-24 15:06 UTC
