### ISSUE TITLE
Getting started tutorial create an asset volume is missing filesystem instructions

### ISSUE THREAD

**Issue by marionnewlevant** [craftcms/docs#471] opened 2023-02-08 05:01 UTC
https://craftcms.com/docs/getting-started-tutorial/configure/section.html#create-an-asset-volume

Has this:
We’ll create a local Asset Volume within the web root for blog post images:

In the control panel, navigate to Settings → Assets.
Choose + New volume.
Enter the name “Blog” and set the following:
Assets in this volume have public URLs: on/enabled
Base URL: @web/assets/blog
File System Path: @webroot/assets/blog
Save the Asset Volume.

It looks to me as if it should say something about creating a Filesystem

**Comment by AugustMiller** [comment] 2023-02-09 21:28
Thanks for submitting! I believe this is a duplicate of #401. I have some pending changes for the tutorial, which I hope to release in the coming week or two. ❤️

**Closed as completed by AugustMiller** 2023-02-09 21:28 UTC
