### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by ljclark** [craftcms/docs#17] opened 2017-05-02 16:17 UTC
Getting the above error when trying to install the beta. Showing the following errors:

```
Problem 1
    - craftcms/cms 3.0.0-beta.13 requires bower-asset/timepicker 1.11.10.0 -> no matching package found.
    - craftcms/cms 3.0.0-beta.12 requires bower-asset/timepicker 1.11.10.0 -> no matching package found.
    - craftcms/cms 3.0.0-beta.11 requires bower-asset/timepicker 1.11.10.0 -> no matching package found.
    - craftcms/cms 3.0.0-beta.10 requires bower-asset/timepicker 1.11.10.0 -> no matching package found.
    - Installation request for craftcms/cms ^3.0.0-beta.10 -> satisfiable by craftcms/cms[3.0.0-beta.10, 3.0.0-beta.11, 3.0.0-beta.12, 3.0.0-beta.13].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```

Any suggestions?

**Comment by brandonkelly** [comment] 2017-05-02 16:21
Duplicate of #1681

**Closed by brandonkelly** 2017-05-02 16:21 UTC

**Comment by brandonkelly** [comment] 2017-05-02 20:41
Beta 14 was just released with a fix.
