### ISSUE TITLE
[Content]: Drafts & Revisions page is empty

### ISSUE THREAD

**Issue by ryanleichty** [craftcms/docs#668] opened 2024-10-23 15:03 UTC
### Product

Craft CMS

### Description

The Drafts & Revisions page is empty

https://craftcms.com/docs/5.x/system/drafts-revisions.html

**Comment by AugustMiller** [comment] 2024-11-08 01:08
Duplicate of #646!

**Closed as completed by AugustMiller** 2024-11-08 01:08 UTC
