### ISSUE TITLE
Installing my plugin shows error: Call to a member function getVersion() on null

### ISSUE THREAD

**Issue by vhontar** [craftcms/docs#32] opened 2017-09-30 10:19 UTC
### Description
Hi, i am using craft3 beta 28.
I am trying to create my own plugin using your docs. I created folder, added composer.json to root, next step i created src folder with Plugin.php in it, and added just one method init(). That's all. Then in the composer in craft project i added repository to this plugin and installed it to the project. Then i opened settings->plugins, then i clicked in install button and got this error.

I had successfully installed https://github.com/craftcms/contact-form plugin to the project without error before i tried to install mine plugin.
I run craft in docker containers. Maybe it's somehow cause this error, but i had successfully installed contact-form plugin.

Maybe i something missed. But i used your docs, just `Intro to Plugin Dev`.

i hope you help to find out what i did wrong or what i should do to make plugin works. Thank you for your help.
### Steps to reproduce

1. `Intro to Plugin Dev`

### Additional info

- Craft version: 3 beta 28
- PHP version: 7.0
- Database driver & version: mysql:5.6

**Comment by brandonkelly** [comment] 2017-09-30 17:32
Duplicate of craftcms/cms#2012

**Closed by brandonkelly** 2017-09-30 17:32 UTC
